baseURL = "http://shib.net.in/"
languageCode = "en-us"
title = "Shib's SRE Blog!"
theme = "archie"
paginate = 5 
Copyright = "Â© 2023 Shib"
canonifyurls = true
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode = "toggle"
	useCDN = false
	subtitle = "All things about SRE, DevOps and Automation!"
	mathjax = true
	katex = true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/shibhikkiran"

[[menu.main]]
name = "Home"
weight = 1
identifier = "home"
pre = "<br />"
url = "/"

[[menu.main]]
name = "Posts"
weight = 2 
identifier = "posts"
pre = "<br />"
url = "/posts"

[[menu.main]]
name = "Tags"
weight = 3 
identifier = "tags"
pre = "<br />"
url = "/tags"


[[menu.main]]
name = "About"
weight = 4 
identifier = "about"
pre = "<br />"
url = "/about"

